import{a as v,S,i}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",R="51706483-b1178684cf0cda85acd7b38c0";async function f(o,e=1){const r={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await v.get(q,{params:r})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".load-more"),h=document.querySelector(".loader"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",e),B.refresh()}function E(){m.innerHTML=""}function g(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const w=document.querySelector(".form"),M=w.elements["search-text"],$=document.querySelector(".load-more");let a="",n=1,u=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),a=M.value.trim(),n=1,a===""){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}E(),d(),g();try{const e=await f(a,n);if(u=e.totalHits,e.hits.length===0){i.info({title:"No Results",message:"No images match your query.",position:"topRight"});return}y(e.hits),n*15<u&&b()}catch{i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{L()}});function O(){const o=document.querySelector(".gallery .gallery-item");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}$.addEventListener("click",async()=>{n+=1,g(),d();try{const o=await f(a,n);y(o.hits),O(),n*15>=u?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
