import{a as E,S as B,i}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const P="https://pixabay.com/api/",M="51706483-b1178684cf0cda85acd7b38c0",f=15;async function h(s,o=1){const e={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:f};return(await E.get(P,{params:e})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".load-more"),g=document.querySelector(".loader"),L=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const o=s.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),L.refresh()}function m(){p.innerHTML=""}function w(){g.classList.remove("hidden")}function v(){g.classList.add("hidden")}function S(){y.classList.remove("hidden")}function a(){y.classList.add("hidden")}function q(){L.refresh()}const R=document.querySelector(".form"),$=R.elements["search-text"],x=document.querySelector(".load-more");let l="",n=1,c=0;R.addEventListener("submit",async s=>{s.preventDefault();const o=$.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}o!==l&&(l=o,n=1,c=0,m(),a()),w();try{const e=await h(l,n);if(c=e.totalHits,e.hits.length===0){i.info({title:"No Results",message:"No images match your query.",position:"topRight"}),a(),m();return}b(e.hits),q(),n*f<c?S():a()}catch{i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{v()}});x.addEventListener("click",async()=>{n+=1,w(),a();try{const s=await h(l,n);b(s.hits),q(),O(),n*f>=c?(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{v()}});function O(){const o=document.querySelector(".gallery").firstElementChild;if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
